// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: provider.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                    // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                               // Error message or success message
	ManifestJson  []byte                 `protobuf:"bytes,3,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"` // JSON serialized PluginManifest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GetManifestResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetManifestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetManifestResponse) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

type InvokeServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 服务名称: "chat", "embed", "text-to-image" 等
	RequestData   []byte                 `protobuf:"bytes,2,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"` // JSON 格式的请求数据
	AuthInfo      string                 `protobuf:"bytes,3,opt,name=auth_info,json=authInfo,proto3" json:"auth_info,omitempty"`          // 认证信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeServiceRequest) Reset() {
	*x = InvokeServiceRequest{}
	mi := &file_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeServiceRequest) ProtoMessage() {}

func (x *InvokeServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeServiceRequest.ProtoReflect.Descriptor instead.
func (*InvokeServiceRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *InvokeServiceRequest) GetRequestData() []byte {
	if x != nil {
		return x.RequestData
	}
	return nil
}

func (x *InvokeServiceRequest) GetAuthInfo() string {
	if x != nil {
		return x.AuthInfo
	}
	return ""
}

type InvokeServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                    // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                               // Error message or success message
	ResponseData  []byte                 `protobuf:"bytes,3,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"` // JSON format response data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeServiceResponse) Reset() {
	*x = InvokeServiceResponse{}
	mi := &file_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeServiceResponse) ProtoMessage() {}

func (x *InvokeServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeServiceResponse.ProtoReflect.Descriptor instead.
func (*InvokeServiceResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeServiceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InvokeServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvokeServiceResponse) GetResponseData() []byte {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

type SetAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthType      string                 `protobuf:"bytes,1,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`                                                                 // Auth type: "apikey", "token", "sign", "oauth"
	Credentials   map[string]string      `protobuf:"bytes,2,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Authentication credentials
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAuthRequest) Reset() {
	*x = SetAuthRequest{}
	mi := &file_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAuthRequest) ProtoMessage() {}

func (x *SetAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAuthRequest.ProtoReflect.Descriptor instead.
func (*SetAuthRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{4}
}

func (x *SetAuthRequest) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *SetAuthRequest) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type SetAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAuthResponse) Reset() {
	*x = SetAuthResponse{}
	mi := &file_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAuthResponse) ProtoMessage() {}

func (x *SetAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAuthResponse.ProtoReflect.Descriptor instead.
func (*SetAuthResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{5}
}

func (x *SetAuthResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SetAuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAuthRequest) Reset() {
	*x = ValidateAuthRequest{}
	mi := &file_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAuthRequest) ProtoMessage() {}

func (x *ValidateAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAuthRequest.ProtoReflect.Descriptor instead.
func (*ValidateAuthRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{6}
}

type ValidateAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAuthResponse) Reset() {
	*x = ValidateAuthResponse{}
	mi := &file_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAuthResponse) ProtoMessage() {}

func (x *ValidateAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAuthResponse.ProtoReflect.Descriptor instead.
func (*ValidateAuthResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateAuthResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ValidateAuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RefreshAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthRequest) Reset() {
	*x = RefreshAuthRequest{}
	mi := &file_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthRequest) ProtoMessage() {}

func (x *RefreshAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthRequest.ProtoReflect.Descriptor instead.
func (*RefreshAuthRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{8}
}

type RefreshAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthResponse) Reset() {
	*x = RefreshAuthResponse{}
	mi := &file_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthResponse) ProtoMessage() {}

func (x *RefreshAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthResponse.ProtoReflect.Descriptor instead.
func (*RefreshAuthResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshAuthResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RefreshAuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartEngineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"` // "cpu", "gpu", "auto"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEngineRequest) Reset() {
	*x = StartEngineRequest{}
	mi := &file_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEngineRequest) ProtoMessage() {}

func (x *StartEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEngineRequest.ProtoReflect.Descriptor instead.
func (*StartEngineRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{10}
}

func (x *StartEngineRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type StartEngineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEngineResponse) Reset() {
	*x = StartEngineResponse{}
	mi := &file_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEngineResponse) ProtoMessage() {}

func (x *StartEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEngineResponse.ProtoReflect.Descriptor instead.
func (*StartEngineResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{11}
}

func (x *StartEngineResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StartEngineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopEngineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopEngineRequest) Reset() {
	*x = StopEngineRequest{}
	mi := &file_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEngineRequest) ProtoMessage() {}

func (x *StopEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEngineRequest.ProtoReflect.Descriptor instead.
func (*StopEngineRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{12}
}

type StopEngineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopEngineResponse) Reset() {
	*x = StopEngineResponse{}
	mi := &file_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEngineResponse) ProtoMessage() {}

func (x *StopEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEngineResponse.ProtoReflect.Descriptor instead.
func (*StopEngineResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{13}
}

func (x *StopEngineResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StopEngineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{14}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{16}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                              // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                         // Error message or success message
	ConfigJson    []byte                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // JSON serialized EngineConfig
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{17}
}

func (x *GetConfigResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetConfigResponse) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type CheckEngineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEngineRequest) Reset() {
	*x = CheckEngineRequest{}
	mi := &file_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEngineRequest) ProtoMessage() {}

func (x *CheckEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEngineRequest.ProtoReflect.Descriptor instead.
func (*CheckEngineRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{18}
}

type CheckEngineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`           // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`      // Error message or success message
	Installed     bool                   `protobuf:"varint,3,opt,name=installed,proto3" json:"installed,omitempty"` // Whether installed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEngineResponse) Reset() {
	*x = CheckEngineResponse{}
	mi := &file_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEngineResponse) ProtoMessage() {}

func (x *CheckEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEngineResponse.ProtoReflect.Descriptor instead.
func (*CheckEngineResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{19}
}

func (x *CheckEngineResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckEngineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckEngineResponse) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

type InstallEngineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cover         bool                   `protobuf:"varint,1,opt,name=cover,proto3" json:"cover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallEngineRequest) Reset() {
	*x = InstallEngineRequest{}
	mi := &file_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallEngineRequest) ProtoMessage() {}

func (x *InstallEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallEngineRequest.ProtoReflect.Descriptor instead.
func (*InstallEngineRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{20}
}

func (x *InstallEngineRequest) GetCover() bool {
	if x != nil {
		return x.Cover
	}
	return false
}

type InstallEngineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallEngineResponse) Reset() {
	*x = InstallEngineResponse{}
	mi := &file_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallEngineResponse) ProtoMessage() {}

func (x *InstallEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallEngineResponse.ProtoReflect.Descriptor instead.
func (*InstallEngineResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{21}
}

func (x *InstallEngineResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InstallEngineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InitEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEnvRequest) Reset() {
	*x = InitEnvRequest{}
	mi := &file_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEnvRequest) ProtoMessage() {}

func (x *InitEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEnvRequest.ProtoReflect.Descriptor instead.
func (*InitEnvRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{22}
}

type InitEnvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEnvResponse) Reset() {
	*x = InitEnvResponse{}
	mi := &file_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEnvResponse) ProtoMessage() {}

func (x *InitEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEnvResponse.ProtoReflect.Descriptor instead.
func (*InitEnvResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{23}
}

func (x *InitEnvResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InitEnvResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpgradeEngineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeEngineRequest) Reset() {
	*x = UpgradeEngineRequest{}
	mi := &file_provider_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeEngineRequest) ProtoMessage() {}

func (x *UpgradeEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeEngineRequest.ProtoReflect.Descriptor instead.
func (*UpgradeEngineRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{24}
}

type UpgradeEngineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeEngineResponse) Reset() {
	*x = UpgradeEngineResponse{}
	mi := &file_provider_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeEngineResponse) ProtoMessage() {}

func (x *UpgradeEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeEngineResponse.ProtoReflect.Descriptor instead.
func (*UpgradeEngineResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{25}
}

func (x *UpgradeEngineResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpgradeEngineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PullModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   []byte                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"` // JSON serialized PullModelRequest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullModelRequest) Reset() {
	*x = PullModelRequest{}
	mi := &file_provider_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullModelRequest) ProtoMessage() {}

func (x *PullModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullModelRequest.ProtoReflect.Descriptor instead.
func (*PullModelRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{26}
}

func (x *PullModelRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

type PullModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                    // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                               // Error message or success message
	ResponseJson  []byte                 `protobuf:"bytes,3,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"` // JSON serialized ProgressResponse
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullModelResponse) Reset() {
	*x = PullModelResponse{}
	mi := &file_provider_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullModelResponse) ProtoMessage() {}

func (x *PullModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullModelResponse.ProtoReflect.Descriptor instead.
func (*PullModelResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{27}
}

func (x *PullModelResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PullModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PullModelResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type PullModelStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   []byte                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullModelStreamRequest) Reset() {
	*x = PullModelStreamRequest{}
	mi := &file_provider_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullModelStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullModelStreamRequest) ProtoMessage() {}

func (x *PullModelStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullModelStreamRequest.ProtoReflect.Descriptor instead.
func (*PullModelStreamRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{28}
}

func (x *PullModelStreamRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

type PullModelStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`       // Stream data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullModelStreamResponse) Reset() {
	*x = PullModelStreamResponse{}
	mi := &file_provider_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullModelStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullModelStreamResponse) ProtoMessage() {}

func (x *PullModelStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullModelStreamResponse.ProtoReflect.Descriptor instead.
func (*PullModelStreamResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{29}
}

func (x *PullModelStreamResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PullModelStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PullModelStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   []byte                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"` // JSON serialized DeleteRequest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_provider_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteModelRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

type DeleteModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelResponse) Reset() {
	*x = DeleteModelResponse{}
	mi := &file_provider_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelResponse) ProtoMessage() {}

func (x *DeleteModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteModelResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_provider_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{32}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                    // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                               // Error message or success message
	ResponseJson  []byte                 `protobuf:"bytes,3,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"` // JSON serialized ListModelsResponse
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_provider_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{33}
}

func (x *ListModelsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListModelsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListModelsResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type LoadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   []byte                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"` // JSON serialized LoadModelRequest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_provider_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{34}
}

func (x *LoadModelRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

type LoadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	mi := &file_provider_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{35}
}

func (x *LoadModelResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoadModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   []byte                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"` // JSON serialized UnloadModelRequest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelRequest) Reset() {
	*x = UnloadModelRequest{}
	mi := &file_provider_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelRequest) ProtoMessage() {}

func (x *UnloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{36}
}

func (x *UnloadModelRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

type UnloadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelResponse) Reset() {
	*x = UnloadModelResponse{}
	mi := &file_provider_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelResponse) ProtoMessage() {}

func (x *UnloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelResponse.ProtoReflect.Descriptor instead.
func (*UnloadModelResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{37}
}

func (x *UnloadModelResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnloadModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRunningModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunningModelsRequest) Reset() {
	*x = GetRunningModelsRequest{}
	mi := &file_provider_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunningModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunningModelsRequest) ProtoMessage() {}

func (x *GetRunningModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunningModelsRequest.ProtoReflect.Descriptor instead.
func (*GetRunningModelsRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{38}
}

type GetRunningModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                    // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                               // Error message or success message
	ResponseJson  []byte                 `protobuf:"bytes,3,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"` // JSON serialized ListModelsResponse
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunningModelsResponse) Reset() {
	*x = GetRunningModelsResponse{}
	mi := &file_provider_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunningModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunningModelsResponse) ProtoMessage() {}

func (x *GetRunningModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunningModelsResponse.ProtoReflect.Descriptor instead.
func (*GetRunningModelsResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{39}
}

func (x *GetRunningModelsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRunningModelsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRunningModelsResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestJson   []byte                 `protobuf:"bytes,1,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"` // JSON serialized EngineVersionResponse (as template)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_provider_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{40}
}

func (x *GetVersionRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                    // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                               // Error message or success message
	ResponseJson  []byte                 `protobuf:"bytes,3,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"` // JSON serialized EngineVersionResponse
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_provider_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{41}
}

func (x *GetVersionResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetVersionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetVersionResponse) GetResponseJson() []byte {
	if x != nil {
		return x.ResponseJson
	}
	return nil
}

type GetOperateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperateStatusRequest) Reset() {
	*x = GetOperateStatusRequest{}
	mi := &file_provider_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperateStatusRequest) ProtoMessage() {}

func (x *GetOperateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperateStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOperateStatusRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{42}
}

type GetOperateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperateStatusResponse) Reset() {
	*x = GetOperateStatusResponse{}
	mi := &file_provider_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperateStatusResponse) ProtoMessage() {}

func (x *GetOperateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperateStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOperateStatusResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{43}
}

func (x *GetOperateStatusResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type SetOperateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOperateStatusRequest) Reset() {
	*x = SetOperateStatusRequest{}
	mi := &file_provider_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOperateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOperateStatusRequest) ProtoMessage() {}

func (x *SetOperateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOperateStatusRequest.ProtoReflect.Descriptor instead.
func (*SetOperateStatusRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{44}
}

func (x *SetOperateStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type SetOperateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOperateStatusResponse) Reset() {
	*x = SetOperateStatusResponse{}
	mi := &file_provider_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOperateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOperateStatusResponse) ProtoMessage() {}

func (x *SetOperateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOperateStatusResponse.ProtoReflect.Descriptor instead.
func (*SetOperateStatusResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{45}
}

// InvokeServiceStreamResponse server-side streaming response
// Used for transferring streaming data from plugin to AOG
type InvokeServiceStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                                                                  // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                             // Error message or success message
	ChunkData     []byte                 `protobuf:"bytes,3,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`                                                        // Streaming data chunk
	IsFinal       bool                   `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`                                                             // Whether this is the final chunk
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadata (e.g., content-type)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeServiceStreamResponse) Reset() {
	*x = InvokeServiceStreamResponse{}
	mi := &file_provider_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeServiceStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeServiceStreamResponse) ProtoMessage() {}

func (x *InvokeServiceStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeServiceStreamResponse.ProtoReflect.Descriptor instead.
func (*InvokeServiceStreamResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{46}
}

func (x *InvokeServiceStreamResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InvokeServiceStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvokeServiceStreamResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *InvokeServiceStreamResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *InvokeServiceStreamResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// InvokeServiceBidiRequest bidirectional streaming request
// Used for bidirectional communication scenarios like WebSocket
type InvokeServiceBidiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                                                  // Service name (only in first message)
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                                                                   // Data chunk
	MessageType   string                 `protobuf:"bytes,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`                                                  // Message type: "text", "binary", "ping", "pong", "close"
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadata
	IsFirst       bool                   `protobuf:"varint,5,opt,name=is_first,json=isFirst,proto3" json:"is_first,omitempty"`                                                             // Whether this is the first message
	AuthInfo      string                 `protobuf:"bytes,6,opt,name=auth_info,json=authInfo,proto3" json:"auth_info,omitempty"`                                                           // remote auth (only in first message)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeServiceBidiRequest) Reset() {
	*x = InvokeServiceBidiRequest{}
	mi := &file_provider_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeServiceBidiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeServiceBidiRequest) ProtoMessage() {}

func (x *InvokeServiceBidiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeServiceBidiRequest.ProtoReflect.Descriptor instead.
func (*InvokeServiceBidiRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{47}
}

func (x *InvokeServiceBidiRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *InvokeServiceBidiRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InvokeServiceBidiRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *InvokeServiceBidiRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InvokeServiceBidiRequest) GetIsFirst() bool {
	if x != nil {
		return x.IsFirst
	}
	return false
}

func (x *InvokeServiceBidiRequest) GetAuthInfo() string {
	if x != nil {
		return x.AuthInfo
	}
	return ""
}

// InvokeServiceBidiResponse bidirectional streaming response
// Used for bidirectional communication scenarios like WebSocket
type InvokeServiceBidiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                                                                  // Error code: 0 or 200 = success, other = failure
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                             // Error message or success message
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                                                                   // Response data chunk
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`                                                  // Message type: "text", "binary", "ping", "pong", "close"
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeServiceBidiResponse) Reset() {
	*x = InvokeServiceBidiResponse{}
	mi := &file_provider_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeServiceBidiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeServiceBidiResponse) ProtoMessage() {}

func (x *InvokeServiceBidiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeServiceBidiResponse.ProtoReflect.Descriptor instead.
func (*InvokeServiceBidiResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{48}
}

func (x *InvokeServiceBidiResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InvokeServiceBidiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvokeServiceBidiResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InvokeServiceBidiResponse) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *InvokeServiceBidiResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_provider_proto protoreflect.FileDescriptor

const file_provider_proto_rawDesc = "" +
	"\n" +
	"\x0eprovider.proto\x12\bprotocol\"\x14\n" +
	"\x12GetManifestRequest\"h\n" +
	"\x13GetManifestResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rmanifest_json\x18\x03 \x01(\fR\fmanifestJson\"y\n" +
	"\x14InvokeServiceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12!\n" +
	"\frequest_data\x18\x02 \x01(\fR\vrequestData\x12\x1b\n" +
	"\tauth_info\x18\x03 \x01(\tR\bauthInfo\"j\n" +
	"\x15InvokeServiceResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rresponse_data\x18\x03 \x01(\fR\fresponseData\"\xba\x01\n" +
	"\x0eSetAuthRequest\x12\x1b\n" +
	"\tauth_type\x18\x01 \x01(\tR\bauthType\x12K\n" +
	"\vcredentials\x18\x02 \x03(\v2).protocol.SetAuthRequest.CredentialsEntryR\vcredentials\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x0fSetAuthResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13ValidateAuthRequest\"D\n" +
	"\x14ValidateAuthResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12RefreshAuthRequest\"C\n" +
	"\x13RefreshAuthResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\x12StartEngineRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\"C\n" +
	"\x13StartEngineResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11StopEngineRequest\"B\n" +
	"\x12StopEngineResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12HealthCheckRequest\"C\n" +
	"\x13HealthCheckResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10GetConfigRequest\"b\n" +
	"\x11GetConfigResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\fR\n" +
	"configJson\"\x14\n" +
	"\x12CheckEngineRequest\"a\n" +
	"\x13CheckEngineResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tinstalled\x18\x03 \x01(\bR\tinstalled\",\n" +
	"\x14InstallEngineRequest\x12\x14\n" +
	"\x05cover\x18\x01 \x01(\bR\x05cover\"E\n" +
	"\x15InstallEngineResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x10\n" +
	"\x0eInitEnvRequest\"?\n" +
	"\x0fInitEnvResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x16\n" +
	"\x14UpgradeEngineRequest\"E\n" +
	"\x15UpgradeEngineResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x10PullModelRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\fR\vrequestJson\"f\n" +
	"\x11PullModelResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rresponse_json\x18\x03 \x01(\fR\fresponseJson\";\n" +
	"\x16PullModelStreamRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\fR\vrequestJson\"[\n" +
	"\x17PullModelStreamResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"7\n" +
	"\x12DeleteModelRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\fR\vrequestJson\"C\n" +
	"\x13DeleteModelResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11ListModelsRequest\"g\n" +
	"\x12ListModelsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rresponse_json\x18\x03 \x01(\fR\fresponseJson\"5\n" +
	"\x10LoadModelRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\fR\vrequestJson\"A\n" +
	"\x11LoadModelResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\x12UnloadModelRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\fR\vrequestJson\"C\n" +
	"\x13UnloadModelResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x19\n" +
	"\x17GetRunningModelsRequest\"m\n" +
	"\x18GetRunningModelsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rresponse_json\x18\x03 \x01(\fR\fresponseJson\"6\n" +
	"\x11GetVersionRequest\x12!\n" +
	"\frequest_json\x18\x01 \x01(\fR\vrequestJson\"g\n" +
	"\x12GetVersionResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rresponse_json\x18\x03 \x01(\fR\fresponseJson\"\x19\n" +
	"\x17GetOperateStatusRequest\"2\n" +
	"\x18GetOperateStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"1\n" +
	"\x17SetOperateStatusRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\x1a\n" +
	"\x18SetOperateStatusResponse\"\x93\x02\n" +
	"\x1bInvokeServiceStreamResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x03 \x01(\fR\tchunkData\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\x12O\n" +
	"\bmetadata\x18\x05 \x03(\v23.protocol.InvokeServiceStreamResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x02\n" +
	"\x18InvokeServiceBidiRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\tR\vmessageType\x12L\n" +
	"\bmetadata\x18\x04 \x03(\v20.protocol.InvokeServiceBidiRequest.MetadataEntryR\bmetadata\x12\x19\n" +
	"\bis_first\x18\x05 \x01(\bR\aisFirst\x12\x1b\n" +
	"\tauth_info\x18\x06 \x01(\tR\bauthInfo\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x02\n" +
	"\x19InvokeServiceBidiResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12M\n" +
	"\bmetadata\x18\x05 \x03(\v21.protocol.InvokeServiceBidiResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc4\x0f\n" +
	"\x0fProviderService\x12J\n" +
	"\vGetManifest\x12\x1c.protocol.GetManifestRequest\x1a\x1d.protocol.GetManifestResponse\x12P\n" +
	"\rInvokeService\x12\x1e.protocol.InvokeServiceRequest\x1a\x1f.protocol.InvokeServiceResponse\x12^\n" +
	"\x13InvokeServiceStream\x12\x1e.protocol.InvokeServiceRequest\x1a%.protocol.InvokeServiceStreamResponse0\x01\x12`\n" +
	"\x11InvokeServiceBidi\x12\".protocol.InvokeServiceBidiRequest\x1a#.protocol.InvokeServiceBidiResponse(\x010\x01\x12J\n" +
	"\vHealthCheck\x12\x1c.protocol.HealthCheckRequest\x1a\x1d.protocol.HealthCheckResponse\x12Y\n" +
	"\x10GetOperateStatus\x12!.protocol.GetOperateStatusRequest\x1a\".protocol.GetOperateStatusResponse\x12Y\n" +
	"\x10SetOperateStatus\x12!.protocol.SetOperateStatusRequest\x1a\".protocol.SetOperateStatusResponse\x12>\n" +
	"\aSetAuth\x12\x18.protocol.SetAuthRequest\x1a\x19.protocol.SetAuthResponse\x12M\n" +
	"\fValidateAuth\x12\x1d.protocol.ValidateAuthRequest\x1a\x1e.protocol.ValidateAuthResponse\x12J\n" +
	"\vRefreshAuth\x12\x1c.protocol.RefreshAuthRequest\x1a\x1d.protocol.RefreshAuthResponse\x12J\n" +
	"\vStartEngine\x12\x1c.protocol.StartEngineRequest\x1a\x1d.protocol.StartEngineResponse\x12G\n" +
	"\n" +
	"StopEngine\x12\x1b.protocol.StopEngineRequest\x1a\x1c.protocol.StopEngineResponse\x12D\n" +
	"\tGetConfig\x12\x1a.protocol.GetConfigRequest\x1a\x1b.protocol.GetConfigResponse\x12J\n" +
	"\vCheckEngine\x12\x1c.protocol.CheckEngineRequest\x1a\x1d.protocol.CheckEngineResponse\x12P\n" +
	"\rInstallEngine\x12\x1e.protocol.InstallEngineRequest\x1a\x1f.protocol.InstallEngineResponse\x12>\n" +
	"\aInitEnv\x12\x18.protocol.InitEnvRequest\x1a\x19.protocol.InitEnvResponse\x12P\n" +
	"\rUpgradeEngine\x12\x1e.protocol.UpgradeEngineRequest\x1a\x1f.protocol.UpgradeEngineResponse\x12D\n" +
	"\tPullModel\x12\x1a.protocol.PullModelRequest\x1a\x1b.protocol.PullModelResponse\x12X\n" +
	"\x0fPullModelStream\x12 .protocol.PullModelStreamRequest\x1a!.protocol.PullModelStreamResponse0\x01\x12J\n" +
	"\vDeleteModel\x12\x1c.protocol.DeleteModelRequest\x1a\x1d.protocol.DeleteModelResponse\x12G\n" +
	"\n" +
	"ListModels\x12\x1b.protocol.ListModelsRequest\x1a\x1c.protocol.ListModelsResponse\x12D\n" +
	"\tLoadModel\x12\x1a.protocol.LoadModelRequest\x1a\x1b.protocol.LoadModelResponse\x12J\n" +
	"\vUnloadModel\x12\x1c.protocol.UnloadModelRequest\x1a\x1d.protocol.UnloadModelResponse\x12Y\n" +
	"\x10GetRunningModels\x12!.protocol.GetRunningModelsRequest\x1a\".protocol.GetRunningModelsResponse\x12G\n" +
	"\n" +
	"GetVersion\x12\x1b.protocol.GetVersionRequest\x1a\x1c.protocol.GetVersionResponseB*Z(github.com/intel/aog/plugin-sdk/protocolb\x06proto3"

var (
	file_provider_proto_rawDescOnce sync.Once
	file_provider_proto_rawDescData []byte
)

func file_provider_proto_rawDescGZIP() []byte {
	file_provider_proto_rawDescOnce.Do(func() {
		file_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)))
	})
	return file_provider_proto_rawDescData
}

var file_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 53)
var file_provider_proto_goTypes = []any{
	(*GetManifestRequest)(nil),          // 0: protocol.GetManifestRequest
	(*GetManifestResponse)(nil),         // 1: protocol.GetManifestResponse
	(*InvokeServiceRequest)(nil),        // 2: protocol.InvokeServiceRequest
	(*InvokeServiceResponse)(nil),       // 3: protocol.InvokeServiceResponse
	(*SetAuthRequest)(nil),              // 4: protocol.SetAuthRequest
	(*SetAuthResponse)(nil),             // 5: protocol.SetAuthResponse
	(*ValidateAuthRequest)(nil),         // 6: protocol.ValidateAuthRequest
	(*ValidateAuthResponse)(nil),        // 7: protocol.ValidateAuthResponse
	(*RefreshAuthRequest)(nil),          // 8: protocol.RefreshAuthRequest
	(*RefreshAuthResponse)(nil),         // 9: protocol.RefreshAuthResponse
	(*StartEngineRequest)(nil),          // 10: protocol.StartEngineRequest
	(*StartEngineResponse)(nil),         // 11: protocol.StartEngineResponse
	(*StopEngineRequest)(nil),           // 12: protocol.StopEngineRequest
	(*StopEngineResponse)(nil),          // 13: protocol.StopEngineResponse
	(*HealthCheckRequest)(nil),          // 14: protocol.HealthCheckRequest
	(*HealthCheckResponse)(nil),         // 15: protocol.HealthCheckResponse
	(*GetConfigRequest)(nil),            // 16: protocol.GetConfigRequest
	(*GetConfigResponse)(nil),           // 17: protocol.GetConfigResponse
	(*CheckEngineRequest)(nil),          // 18: protocol.CheckEngineRequest
	(*CheckEngineResponse)(nil),         // 19: protocol.CheckEngineResponse
	(*InstallEngineRequest)(nil),        // 20: protocol.InstallEngineRequest
	(*InstallEngineResponse)(nil),       // 21: protocol.InstallEngineResponse
	(*InitEnvRequest)(nil),              // 22: protocol.InitEnvRequest
	(*InitEnvResponse)(nil),             // 23: protocol.InitEnvResponse
	(*UpgradeEngineRequest)(nil),        // 24: protocol.UpgradeEngineRequest
	(*UpgradeEngineResponse)(nil),       // 25: protocol.UpgradeEngineResponse
	(*PullModelRequest)(nil),            // 26: protocol.PullModelRequest
	(*PullModelResponse)(nil),           // 27: protocol.PullModelResponse
	(*PullModelStreamRequest)(nil),      // 28: protocol.PullModelStreamRequest
	(*PullModelStreamResponse)(nil),     // 29: protocol.PullModelStreamResponse
	(*DeleteModelRequest)(nil),          // 30: protocol.DeleteModelRequest
	(*DeleteModelResponse)(nil),         // 31: protocol.DeleteModelResponse
	(*ListModelsRequest)(nil),           // 32: protocol.ListModelsRequest
	(*ListModelsResponse)(nil),          // 33: protocol.ListModelsResponse
	(*LoadModelRequest)(nil),            // 34: protocol.LoadModelRequest
	(*LoadModelResponse)(nil),           // 35: protocol.LoadModelResponse
	(*UnloadModelRequest)(nil),          // 36: protocol.UnloadModelRequest
	(*UnloadModelResponse)(nil),         // 37: protocol.UnloadModelResponse
	(*GetRunningModelsRequest)(nil),     // 38: protocol.GetRunningModelsRequest
	(*GetRunningModelsResponse)(nil),    // 39: protocol.GetRunningModelsResponse
	(*GetVersionRequest)(nil),           // 40: protocol.GetVersionRequest
	(*GetVersionResponse)(nil),          // 41: protocol.GetVersionResponse
	(*GetOperateStatusRequest)(nil),     // 42: protocol.GetOperateStatusRequest
	(*GetOperateStatusResponse)(nil),    // 43: protocol.GetOperateStatusResponse
	(*SetOperateStatusRequest)(nil),     // 44: protocol.SetOperateStatusRequest
	(*SetOperateStatusResponse)(nil),    // 45: protocol.SetOperateStatusResponse
	(*InvokeServiceStreamResponse)(nil), // 46: protocol.InvokeServiceStreamResponse
	(*InvokeServiceBidiRequest)(nil),    // 47: protocol.InvokeServiceBidiRequest
	(*InvokeServiceBidiResponse)(nil),   // 48: protocol.InvokeServiceBidiResponse
	nil,                                 // 49: protocol.SetAuthRequest.CredentialsEntry
	nil,                                 // 50: protocol.InvokeServiceStreamResponse.MetadataEntry
	nil,                                 // 51: protocol.InvokeServiceBidiRequest.MetadataEntry
	nil,                                 // 52: protocol.InvokeServiceBidiResponse.MetadataEntry
}
var file_provider_proto_depIdxs = []int32{
	49, // 0: protocol.SetAuthRequest.credentials:type_name -> protocol.SetAuthRequest.CredentialsEntry
	50, // 1: protocol.InvokeServiceStreamResponse.metadata:type_name -> protocol.InvokeServiceStreamResponse.MetadataEntry
	51, // 2: protocol.InvokeServiceBidiRequest.metadata:type_name -> protocol.InvokeServiceBidiRequest.MetadataEntry
	52, // 3: protocol.InvokeServiceBidiResponse.metadata:type_name -> protocol.InvokeServiceBidiResponse.MetadataEntry
	0,  // 4: protocol.ProviderService.GetManifest:input_type -> protocol.GetManifestRequest
	2,  // 5: protocol.ProviderService.InvokeService:input_type -> protocol.InvokeServiceRequest
	2,  // 6: protocol.ProviderService.InvokeServiceStream:input_type -> protocol.InvokeServiceRequest
	47, // 7: protocol.ProviderService.InvokeServiceBidi:input_type -> protocol.InvokeServiceBidiRequest
	14, // 8: protocol.ProviderService.HealthCheck:input_type -> protocol.HealthCheckRequest
	42, // 9: protocol.ProviderService.GetOperateStatus:input_type -> protocol.GetOperateStatusRequest
	44, // 10: protocol.ProviderService.SetOperateStatus:input_type -> protocol.SetOperateStatusRequest
	4,  // 11: protocol.ProviderService.SetAuth:input_type -> protocol.SetAuthRequest
	6,  // 12: protocol.ProviderService.ValidateAuth:input_type -> protocol.ValidateAuthRequest
	8,  // 13: protocol.ProviderService.RefreshAuth:input_type -> protocol.RefreshAuthRequest
	10, // 14: protocol.ProviderService.StartEngine:input_type -> protocol.StartEngineRequest
	12, // 15: protocol.ProviderService.StopEngine:input_type -> protocol.StopEngineRequest
	16, // 16: protocol.ProviderService.GetConfig:input_type -> protocol.GetConfigRequest
	18, // 17: protocol.ProviderService.CheckEngine:input_type -> protocol.CheckEngineRequest
	20, // 18: protocol.ProviderService.InstallEngine:input_type -> protocol.InstallEngineRequest
	22, // 19: protocol.ProviderService.InitEnv:input_type -> protocol.InitEnvRequest
	24, // 20: protocol.ProviderService.UpgradeEngine:input_type -> protocol.UpgradeEngineRequest
	26, // 21: protocol.ProviderService.PullModel:input_type -> protocol.PullModelRequest
	28, // 22: protocol.ProviderService.PullModelStream:input_type -> protocol.PullModelStreamRequest
	30, // 23: protocol.ProviderService.DeleteModel:input_type -> protocol.DeleteModelRequest
	32, // 24: protocol.ProviderService.ListModels:input_type -> protocol.ListModelsRequest
	34, // 25: protocol.ProviderService.LoadModel:input_type -> protocol.LoadModelRequest
	36, // 26: protocol.ProviderService.UnloadModel:input_type -> protocol.UnloadModelRequest
	38, // 27: protocol.ProviderService.GetRunningModels:input_type -> protocol.GetRunningModelsRequest
	40, // 28: protocol.ProviderService.GetVersion:input_type -> protocol.GetVersionRequest
	1,  // 29: protocol.ProviderService.GetManifest:output_type -> protocol.GetManifestResponse
	3,  // 30: protocol.ProviderService.InvokeService:output_type -> protocol.InvokeServiceResponse
	46, // 31: protocol.ProviderService.InvokeServiceStream:output_type -> protocol.InvokeServiceStreamResponse
	48, // 32: protocol.ProviderService.InvokeServiceBidi:output_type -> protocol.InvokeServiceBidiResponse
	15, // 33: protocol.ProviderService.HealthCheck:output_type -> protocol.HealthCheckResponse
	43, // 34: protocol.ProviderService.GetOperateStatus:output_type -> protocol.GetOperateStatusResponse
	45, // 35: protocol.ProviderService.SetOperateStatus:output_type -> protocol.SetOperateStatusResponse
	5,  // 36: protocol.ProviderService.SetAuth:output_type -> protocol.SetAuthResponse
	7,  // 37: protocol.ProviderService.ValidateAuth:output_type -> protocol.ValidateAuthResponse
	9,  // 38: protocol.ProviderService.RefreshAuth:output_type -> protocol.RefreshAuthResponse
	11, // 39: protocol.ProviderService.StartEngine:output_type -> protocol.StartEngineResponse
	13, // 40: protocol.ProviderService.StopEngine:output_type -> protocol.StopEngineResponse
	17, // 41: protocol.ProviderService.GetConfig:output_type -> protocol.GetConfigResponse
	19, // 42: protocol.ProviderService.CheckEngine:output_type -> protocol.CheckEngineResponse
	21, // 43: protocol.ProviderService.InstallEngine:output_type -> protocol.InstallEngineResponse
	23, // 44: protocol.ProviderService.InitEnv:output_type -> protocol.InitEnvResponse
	25, // 45: protocol.ProviderService.UpgradeEngine:output_type -> protocol.UpgradeEngineResponse
	27, // 46: protocol.ProviderService.PullModel:output_type -> protocol.PullModelResponse
	29, // 47: protocol.ProviderService.PullModelStream:output_type -> protocol.PullModelStreamResponse
	31, // 48: protocol.ProviderService.DeleteModel:output_type -> protocol.DeleteModelResponse
	33, // 49: protocol.ProviderService.ListModels:output_type -> protocol.ListModelsResponse
	35, // 50: protocol.ProviderService.LoadModel:output_type -> protocol.LoadModelResponse
	37, // 51: protocol.ProviderService.UnloadModel:output_type -> protocol.UnloadModelResponse
	39, // 52: protocol.ProviderService.GetRunningModels:output_type -> protocol.GetRunningModelsResponse
	41, // 53: protocol.ProviderService.GetVersion:output_type -> protocol.GetVersionResponse
	29, // [29:54] is the sub-list for method output_type
	4,  // [4:29] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_provider_proto_init() }
func file_provider_proto_init() {
	if File_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   53,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_proto_goTypes,
		DependencyIndexes: file_provider_proto_depIdxs,
		MessageInfos:      file_provider_proto_msgTypes,
	}.Build()
	File_provider_proto = out.File
	file_provider_proto_goTypes = nil
	file_provider_proto_depIdxs = nil
}
