// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0--rc1
// source: provider.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderService_GetManifest_FullMethodName         = "/protocol.ProviderService/GetManifest"
	ProviderService_InvokeService_FullMethodName       = "/protocol.ProviderService/InvokeService"
	ProviderService_InvokeServiceStream_FullMethodName = "/protocol.ProviderService/InvokeServiceStream"
	ProviderService_InvokeServiceBidi_FullMethodName   = "/protocol.ProviderService/InvokeServiceBidi"
	ProviderService_HealthCheck_FullMethodName         = "/protocol.ProviderService/HealthCheck"
	ProviderService_GetOperateStatus_FullMethodName    = "/protocol.ProviderService/GetOperateStatus"
	ProviderService_SetOperateStatus_FullMethodName    = "/protocol.ProviderService/SetOperateStatus"
	ProviderService_SetAuth_FullMethodName             = "/protocol.ProviderService/SetAuth"
	ProviderService_ValidateAuth_FullMethodName        = "/protocol.ProviderService/ValidateAuth"
	ProviderService_RefreshAuth_FullMethodName         = "/protocol.ProviderService/RefreshAuth"
	ProviderService_StartEngine_FullMethodName         = "/protocol.ProviderService/StartEngine"
	ProviderService_StopEngine_FullMethodName          = "/protocol.ProviderService/StopEngine"
	ProviderService_GetConfig_FullMethodName           = "/protocol.ProviderService/GetConfig"
	ProviderService_CheckEngine_FullMethodName         = "/protocol.ProviderService/CheckEngine"
	ProviderService_InstallEngine_FullMethodName       = "/protocol.ProviderService/InstallEngine"
	ProviderService_InitEnv_FullMethodName             = "/protocol.ProviderService/InitEnv"
	ProviderService_UpgradeEngine_FullMethodName       = "/protocol.ProviderService/UpgradeEngine"
	ProviderService_PullModel_FullMethodName           = "/protocol.ProviderService/PullModel"
	ProviderService_PullModelStream_FullMethodName     = "/protocol.ProviderService/PullModelStream"
	ProviderService_DeleteModel_FullMethodName         = "/protocol.ProviderService/DeleteModel"
	ProviderService_ListModels_FullMethodName          = "/protocol.ProviderService/ListModels"
	ProviderService_LoadModel_FullMethodName           = "/protocol.ProviderService/LoadModel"
	ProviderService_UnloadModel_FullMethodName         = "/protocol.ProviderService/UnloadModel"
	ProviderService_GetRunningModels_FullMethodName    = "/protocol.ProviderService/GetRunningModels"
	ProviderService_GetVersion_FullMethodName          = "/protocol.ProviderService/GetVersion"
)

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # ProviderService defines the gRPC service for plugin Provider
//
// Note:
//   - Remote plugins only need to implement partial methods (common methods + Auth methods)
//   - Local plugins need to implement full lifecycle and model management methods
//   - Unimplemented methods will return "not supported" error
type ProviderServiceClient interface {
	// GetManifest returns plugin metadata
	GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error)
	// InvokeService invokes plugin service (core method - unary call)
	InvokeService(ctx context.Context, in *InvokeServiceRequest, opts ...grpc.CallOption) (*InvokeServiceResponse, error)
	// InvokeServiceStream server-side streaming call (for HTTP streaming: SSE/NDJSON)
	// Only called when service declares capabilities.support_streaming = true
	InvokeServiceStream(ctx context.Context, in *InvokeServiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeServiceStreamResponse], error)
	// InvokeServiceBidi bidirectional streaming call (for WebSocket)
	// Only called when service declares protocol = "WEBSOCKET" or capabilities.support_bidirectional = true
	InvokeServiceBidi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InvokeServiceBidiRequest, InvokeServiceBidiResponse], error)
	// HealthCheck performs health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// GetOperateStatus returns operational status
	GetOperateStatus(ctx context.Context, in *GetOperateStatusRequest, opts ...grpc.CallOption) (*GetOperateStatusResponse, error)
	// SetOperateStatus sets operational status
	SetOperateStatus(ctx context.Context, in *SetOperateStatusRequest, opts ...grpc.CallOption) (*SetOperateStatusResponse, error)
	// Remote plugin methods (cloud API plugins)
	SetAuth(ctx context.Context, in *SetAuthRequest, opts ...grpc.CallOption) (*SetAuthResponse, error)
	ValidateAuth(ctx context.Context, in *ValidateAuthRequest, opts ...grpc.CallOption) (*ValidateAuthResponse, error)
	RefreshAuth(ctx context.Context, in *RefreshAuthRequest, opts ...grpc.CallOption) (*RefreshAuthResponse, error)
	// Engine lifecycle management
	StartEngine(ctx context.Context, in *StartEngineRequest, opts ...grpc.CallOption) (*StartEngineResponse, error)
	StopEngine(ctx context.Context, in *StopEngineRequest, opts ...grpc.CallOption) (*StopEngineResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// Engine installation and environment management
	CheckEngine(ctx context.Context, in *CheckEngineRequest, opts ...grpc.CallOption) (*CheckEngineResponse, error)
	InstallEngine(ctx context.Context, in *InstallEngineRequest, opts ...grpc.CallOption) (*InstallEngineResponse, error)
	InitEnv(ctx context.Context, in *InitEnvRequest, opts ...grpc.CallOption) (*InitEnvResponse, error)
	UpgradeEngine(ctx context.Context, in *UpgradeEngineRequest, opts ...grpc.CallOption) (*UpgradeEngineResponse, error)
	// Model management
	PullModel(ctx context.Context, in *PullModelRequest, opts ...grpc.CallOption) (*PullModelResponse, error)
	PullModelStream(ctx context.Context, in *PullModelStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullModelStreamResponse], error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error)
	GetRunningModels(ctx context.Context, in *GetRunningModelsRequest, opts ...grpc.CallOption) (*GetRunningModelsResponse, error)
	// Version information
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManifestResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) InvokeService(ctx context.Context, in *InvokeServiceRequest, opts ...grpc.CallOption) (*InvokeServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeServiceResponse)
	err := c.cc.Invoke(ctx, ProviderService_InvokeService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) InvokeServiceStream(ctx context.Context, in *InvokeServiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeServiceStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProviderService_ServiceDesc.Streams[0], ProviderService_InvokeServiceStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InvokeServiceRequest, InvokeServiceStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_InvokeServiceStreamClient = grpc.ServerStreamingClient[InvokeServiceStreamResponse]

func (c *providerServiceClient) InvokeServiceBidi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InvokeServiceBidiRequest, InvokeServiceBidiResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProviderService_ServiceDesc.Streams[1], ProviderService_InvokeServiceBidi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InvokeServiceBidiRequest, InvokeServiceBidiResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_InvokeServiceBidiClient = grpc.BidiStreamingClient[InvokeServiceBidiRequest, InvokeServiceBidiResponse]

func (c *providerServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ProviderService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetOperateStatus(ctx context.Context, in *GetOperateStatusRequest, opts ...grpc.CallOption) (*GetOperateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperateStatusResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetOperateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) SetOperateStatus(ctx context.Context, in *SetOperateStatusRequest, opts ...grpc.CallOption) (*SetOperateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetOperateStatusResponse)
	err := c.cc.Invoke(ctx, ProviderService_SetOperateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) SetAuth(ctx context.Context, in *SetAuthRequest, opts ...grpc.CallOption) (*SetAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAuthResponse)
	err := c.cc.Invoke(ctx, ProviderService_SetAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ValidateAuth(ctx context.Context, in *ValidateAuthRequest, opts ...grpc.CallOption) (*ValidateAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAuthResponse)
	err := c.cc.Invoke(ctx, ProviderService_ValidateAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) RefreshAuth(ctx context.Context, in *RefreshAuthRequest, opts ...grpc.CallOption) (*RefreshAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshAuthResponse)
	err := c.cc.Invoke(ctx, ProviderService_RefreshAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) StartEngine(ctx context.Context, in *StartEngineRequest, opts ...grpc.CallOption) (*StartEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartEngineResponse)
	err := c.cc.Invoke(ctx, ProviderService_StartEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) StopEngine(ctx context.Context, in *StopEngineRequest, opts ...grpc.CallOption) (*StopEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopEngineResponse)
	err := c.cc.Invoke(ctx, ProviderService_StopEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) CheckEngine(ctx context.Context, in *CheckEngineRequest, opts ...grpc.CallOption) (*CheckEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckEngineResponse)
	err := c.cc.Invoke(ctx, ProviderService_CheckEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) InstallEngine(ctx context.Context, in *InstallEngineRequest, opts ...grpc.CallOption) (*InstallEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallEngineResponse)
	err := c.cc.Invoke(ctx, ProviderService_InstallEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) InitEnv(ctx context.Context, in *InitEnvRequest, opts ...grpc.CallOption) (*InitEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitEnvResponse)
	err := c.cc.Invoke(ctx, ProviderService_InitEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) UpgradeEngine(ctx context.Context, in *UpgradeEngineRequest, opts ...grpc.CallOption) (*UpgradeEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeEngineResponse)
	err := c.cc.Invoke(ctx, ProviderService_UpgradeEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) PullModel(ctx context.Context, in *PullModelRequest, opts ...grpc.CallOption) (*PullModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullModelResponse)
	err := c.cc.Invoke(ctx, ProviderService_PullModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) PullModelStream(ctx context.Context, in *PullModelStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullModelStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProviderService_ServiceDesc.Streams[2], ProviderService_PullModelStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullModelStreamRequest, PullModelStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_PullModelStreamClient = grpc.ServerStreamingClient[PullModelStreamResponse]

func (c *providerServiceClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelResponse)
	err := c.cc.Invoke(ctx, ProviderService_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ProviderService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, ProviderService_LoadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadModelResponse)
	err := c.cc.Invoke(ctx, ProviderService_UnloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetRunningModels(ctx context.Context, in *GetRunningModelsRequest, opts ...grpc.CallOption) (*GetRunningModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunningModelsResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetRunningModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServiceServer is the server API for ProviderService service.
// All implementations must embed UnimplementedProviderServiceServer
// for forward compatibility.
//
// # ProviderService defines the gRPC service for plugin Provider
//
// Note:
//   - Remote plugins only need to implement partial methods (common methods + Auth methods)
//   - Local plugins need to implement full lifecycle and model management methods
//   - Unimplemented methods will return "not supported" error
type ProviderServiceServer interface {
	// GetManifest returns plugin metadata
	GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error)
	// InvokeService invokes plugin service (core method - unary call)
	InvokeService(context.Context, *InvokeServiceRequest) (*InvokeServiceResponse, error)
	// InvokeServiceStream server-side streaming call (for HTTP streaming: SSE/NDJSON)
	// Only called when service declares capabilities.support_streaming = true
	InvokeServiceStream(*InvokeServiceRequest, grpc.ServerStreamingServer[InvokeServiceStreamResponse]) error
	// InvokeServiceBidi bidirectional streaming call (for WebSocket)
	// Only called when service declares protocol = "WEBSOCKET" or capabilities.support_bidirectional = true
	InvokeServiceBidi(grpc.BidiStreamingServer[InvokeServiceBidiRequest, InvokeServiceBidiResponse]) error
	// HealthCheck performs health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// GetOperateStatus returns operational status
	GetOperateStatus(context.Context, *GetOperateStatusRequest) (*GetOperateStatusResponse, error)
	// SetOperateStatus sets operational status
	SetOperateStatus(context.Context, *SetOperateStatusRequest) (*SetOperateStatusResponse, error)
	// Remote plugin methods (cloud API plugins)
	SetAuth(context.Context, *SetAuthRequest) (*SetAuthResponse, error)
	ValidateAuth(context.Context, *ValidateAuthRequest) (*ValidateAuthResponse, error)
	RefreshAuth(context.Context, *RefreshAuthRequest) (*RefreshAuthResponse, error)
	// Engine lifecycle management
	StartEngine(context.Context, *StartEngineRequest) (*StartEngineResponse, error)
	StopEngine(context.Context, *StopEngineRequest) (*StopEngineResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// Engine installation and environment management
	CheckEngine(context.Context, *CheckEngineRequest) (*CheckEngineResponse, error)
	InstallEngine(context.Context, *InstallEngineRequest) (*InstallEngineResponse, error)
	InitEnv(context.Context, *InitEnvRequest) (*InitEnvResponse, error)
	UpgradeEngine(context.Context, *UpgradeEngineRequest) (*UpgradeEngineResponse, error)
	// Model management
	PullModel(context.Context, *PullModelRequest) (*PullModelResponse, error)
	PullModelStream(*PullModelStreamRequest, grpc.ServerStreamingServer[PullModelStreamResponse]) error
	DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error)
	GetRunningModels(context.Context, *GetRunningModelsRequest) (*GetRunningModelsResponse, error)
	// Version information
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	mustEmbedUnimplementedProviderServiceServer()
}

// UnimplementedProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServiceServer struct{}

func (UnimplementedProviderServiceServer) GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedProviderServiceServer) InvokeService(context.Context, *InvokeServiceRequest) (*InvokeServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeService not implemented")
}
func (UnimplementedProviderServiceServer) InvokeServiceStream(*InvokeServiceRequest, grpc.ServerStreamingServer[InvokeServiceStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method InvokeServiceStream not implemented")
}
func (UnimplementedProviderServiceServer) InvokeServiceBidi(grpc.BidiStreamingServer[InvokeServiceBidiRequest, InvokeServiceBidiResponse]) error {
	return status.Errorf(codes.Unimplemented, "method InvokeServiceBidi not implemented")
}
func (UnimplementedProviderServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedProviderServiceServer) GetOperateStatus(context.Context, *GetOperateStatusRequest) (*GetOperateStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperateStatus not implemented")
}
func (UnimplementedProviderServiceServer) SetOperateStatus(context.Context, *SetOperateStatusRequest) (*SetOperateStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetOperateStatus not implemented")
}
func (UnimplementedProviderServiceServer) SetAuth(context.Context, *SetAuthRequest) (*SetAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAuth not implemented")
}
func (UnimplementedProviderServiceServer) ValidateAuth(context.Context, *ValidateAuthRequest) (*ValidateAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAuth not implemented")
}
func (UnimplementedProviderServiceServer) RefreshAuth(context.Context, *RefreshAuthRequest) (*RefreshAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshAuth not implemented")
}
func (UnimplementedProviderServiceServer) StartEngine(context.Context, *StartEngineRequest) (*StartEngineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartEngine not implemented")
}
func (UnimplementedProviderServiceServer) StopEngine(context.Context, *StopEngineRequest) (*StopEngineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopEngine not implemented")
}
func (UnimplementedProviderServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedProviderServiceServer) CheckEngine(context.Context, *CheckEngineRequest) (*CheckEngineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEngine not implemented")
}
func (UnimplementedProviderServiceServer) InstallEngine(context.Context, *InstallEngineRequest) (*InstallEngineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallEngine not implemented")
}
func (UnimplementedProviderServiceServer) InitEnv(context.Context, *InitEnvRequest) (*InitEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitEnv not implemented")
}
func (UnimplementedProviderServiceServer) UpgradeEngine(context.Context, *UpgradeEngineRequest) (*UpgradeEngineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradeEngine not implemented")
}
func (UnimplementedProviderServiceServer) PullModel(context.Context, *PullModelRequest) (*PullModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullModel not implemented")
}
func (UnimplementedProviderServiceServer) PullModelStream(*PullModelStreamRequest, grpc.ServerStreamingServer[PullModelStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PullModelStream not implemented")
}
func (UnimplementedProviderServiceServer) DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedProviderServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedProviderServiceServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedProviderServiceServer) UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedProviderServiceServer) GetRunningModels(context.Context, *GetRunningModelsRequest) (*GetRunningModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunningModels not implemented")
}
func (UnimplementedProviderServiceServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedProviderServiceServer) mustEmbedUnimplementedProviderServiceServer() {}
func (UnimplementedProviderServiceServer) testEmbeddedByValue()                         {}

// UnsafeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServiceServer will
// result in compilation errors.
type UnsafeProviderServiceServer interface {
	mustEmbedUnimplementedProviderServiceServer()
}

func RegisterProviderServiceServer(s grpc.ServiceRegistrar, srv ProviderServiceServer) {
	// If the following call pancis, it indicates UnimplementedProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderService_ServiceDesc, srv)
}

func _ProviderService_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetManifest(ctx, req.(*GetManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_InvokeService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).InvokeService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_InvokeService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).InvokeService(ctx, req.(*InvokeServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_InvokeServiceStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeServiceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServiceServer).InvokeServiceStream(m, &grpc.GenericServerStream[InvokeServiceRequest, InvokeServiceStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_InvokeServiceStreamServer = grpc.ServerStreamingServer[InvokeServiceStreamResponse]

func _ProviderService_InvokeServiceBidi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServiceServer).InvokeServiceBidi(&grpc.GenericServerStream[InvokeServiceBidiRequest, InvokeServiceBidiResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_InvokeServiceBidiServer = grpc.BidiStreamingServer[InvokeServiceBidiRequest, InvokeServiceBidiResponse]

func _ProviderService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetOperateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetOperateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetOperateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetOperateStatus(ctx, req.(*GetOperateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_SetOperateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOperateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).SetOperateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_SetOperateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).SetOperateStatus(ctx, req.(*SetOperateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_SetAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).SetAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_SetAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).SetAuth(ctx, req.(*SetAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ValidateAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ValidateAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ValidateAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ValidateAuth(ctx, req.(*ValidateAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_RefreshAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).RefreshAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_RefreshAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).RefreshAuth(ctx, req.(*RefreshAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_StartEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).StartEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_StartEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).StartEngine(ctx, req.(*StartEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_StopEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).StopEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_StopEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).StopEngine(ctx, req.(*StopEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_CheckEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).CheckEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_CheckEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).CheckEngine(ctx, req.(*CheckEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_InstallEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).InstallEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_InstallEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).InstallEngine(ctx, req.(*InstallEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_InitEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).InitEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_InitEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).InitEnv(ctx, req.(*InitEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_UpgradeEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).UpgradeEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_UpgradeEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).UpgradeEngine(ctx, req.(*UpgradeEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_PullModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).PullModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_PullModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).PullModel(ctx, req.(*PullModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_PullModelStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullModelStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServiceServer).PullModelStream(m, &grpc.GenericServerStream[PullModelStreamRequest, PullModelStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_PullModelStreamServer = grpc.ServerStreamingServer[PullModelStreamResponse]

func _ProviderService_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_UnloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetRunningModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunningModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetRunningModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetRunningModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetRunningModels(ctx, req.(*GetRunningModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderService_ServiceDesc is the grpc.ServiceDesc for ProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifest",
			Handler:    _ProviderService_GetManifest_Handler,
		},
		{
			MethodName: "InvokeService",
			Handler:    _ProviderService_InvokeService_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ProviderService_HealthCheck_Handler,
		},
		{
			MethodName: "GetOperateStatus",
			Handler:    _ProviderService_GetOperateStatus_Handler,
		},
		{
			MethodName: "SetOperateStatus",
			Handler:    _ProviderService_SetOperateStatus_Handler,
		},
		{
			MethodName: "SetAuth",
			Handler:    _ProviderService_SetAuth_Handler,
		},
		{
			MethodName: "ValidateAuth",
			Handler:    _ProviderService_ValidateAuth_Handler,
		},
		{
			MethodName: "RefreshAuth",
			Handler:    _ProviderService_RefreshAuth_Handler,
		},
		{
			MethodName: "StartEngine",
			Handler:    _ProviderService_StartEngine_Handler,
		},
		{
			MethodName: "StopEngine",
			Handler:    _ProviderService_StopEngine_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _ProviderService_GetConfig_Handler,
		},
		{
			MethodName: "CheckEngine",
			Handler:    _ProviderService_CheckEngine_Handler,
		},
		{
			MethodName: "InstallEngine",
			Handler:    _ProviderService_InstallEngine_Handler,
		},
		{
			MethodName: "InitEnv",
			Handler:    _ProviderService_InitEnv_Handler,
		},
		{
			MethodName: "UpgradeEngine",
			Handler:    _ProviderService_UpgradeEngine_Handler,
		},
		{
			MethodName: "PullModel",
			Handler:    _ProviderService_PullModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _ProviderService_DeleteModel_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ProviderService_ListModels_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _ProviderService_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _ProviderService_UnloadModel_Handler,
		},
		{
			MethodName: "GetRunningModels",
			Handler:    _ProviderService_GetRunningModels_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _ProviderService_GetVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokeServiceStream",
			Handler:       _ProviderService_InvokeServiceStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InvokeServiceBidi",
			Handler:       _ProviderService_InvokeServiceBidi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PullModelStream",
			Handler:       _ProviderService_PullModelStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "provider.proto",
}
